# Generated by Django 5.2.1 on 2025-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('內科', '內科'), ('外科', '外科'), ('小兒科', '小兒科'), ('婦產科', '婦產科'), ('耳鼻喉科', '耳鼻喉科'), ('皮膚科', '皮膚科'), ('眼科', '眼科')], default='內科', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='王大明', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('晚上', '晚上')], default='上午', max_length=4),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(default='', max_length=200),
        ),
    ]
